(() => {
  const extra = [
    {title:"3Dフリップカード",className:".edu-3d-flip-card",category:"motion",file:"edu-effects-3d.css",tags:"3D カード 裏返し hover flip",stage:"is-violet",effect:"edu-kinetic-pop",
      preview:'<div class="edu-3d-flip-card"><div class="edu-3d-flip-card__inner"><div class="edu-3d-flip-card__front"><div><strong>表：問題</strong><div class="edu-3d-flip-card__hint">タップ・ホバーで裏返す</div></div></div><div class="edu-3d-flip-card__back"><div><strong>裏：ヒント</strong><div class="edu-3d-flip-card__hint">答えへの手がかり</div></div></div></div></div>',
      copy:'<div class="edu-3d-flip-card"><div class="edu-3d-flip-card__inner"><div class="edu-3d-flip-card__front"><strong>表：問題</strong></div><div class="edu-3d-flip-card__back"><strong>裏：ヒント</strong></div></div></div>'},
    {title:"3Dキューブ",className:".edu-3d-cube",category:"motion",file:"edu-effects-3d.css",tags:"3D キューブ 回転 cube 理科 宇宙",stage:"is-dark",
      preview:'<div class="edu-3d-cube"><div class="edu-3d-cube__body"><span class="edu-3d-cube__face">表</span><span class="edu-3d-cube__face">裏</span><span class="edu-3d-cube__face">右</span><span class="edu-3d-cube__face">左</span><span class="edu-3d-cube__face">上</span><span class="edu-3d-cube__face">下</span></div></div>',
      copy:'<div class="edu-3d-cube"><div class="edu-3d-cube__body"><span class="edu-3d-cube__face">表</span><span class="edu-3d-cube__face">裏</span><span class="edu-3d-cube__face">右</span><span class="edu-3d-cube__face">左</span><span class="edu-3d-cube__face">上</span><span class="edu-3d-cube__face">下</span></div></div>'},
    {title:"3Dメリーゴーランド",className:".edu-3d-carousel",category:"motion",file:"edu-effects-3d.css",tags:"3D カルーセル メリーゴーランド 回転",stage:"is-dark",
      preview:'<div class="edu-3d-carousel"><div class="edu-3d-carousel__track"><span class="edu-3d-carousel__item" style="--i:0">1</span><span class="edu-3d-carousel__item" style="--i:1">2</span><span class="edu-3d-carousel__item" style="--i:2">3</span><span class="edu-3d-carousel__item" style="--i:3">4</span><span class="edu-3d-carousel__item" style="--i:4">5</span><span class="edu-3d-carousel__item" style="--i:5">6</span></div></div>',
      copy:'<div class="edu-3d-carousel"><div class="edu-3d-carousel__track"><span class="edu-3d-carousel__item" style="--i:0">A</span><span class="edu-3d-carousel__item" style="--i:1">B</span><span class="edu-3d-carousel__item" style="--i:2">C</span><span class="edu-3d-carousel__item" style="--i:3">D</span><span class="edu-3d-carousel__item" style="--i:4">E</span><span class="edu-3d-carousel__item" style="--i:5">F</span></div></div>'},
    {title:"カバーフロー",className:".edu-coverflow",category:"motion",file:"edu-effects-3d.css",tags:"3D カバーフロー coverflow スライダー カルーセル",stage:"is-violet",
      preview:'<div class="edu-coverflow"><input id="gallery-coverflow-preview-3" type="radio" name="gallery-coverflow" checked><input id="gallery-coverflow-preview-1" type="radio" name="gallery-coverflow"><input id="gallery-coverflow-preview-2" type="radio" name="gallery-coverflow"><input id="gallery-coverflow-preview-4" type="radio" name="gallery-coverflow"><input id="gallery-coverflow-preview-5" type="radio" name="gallery-coverflow"><div class="edu-coverflow__track"><label class="edu-coverflow__item" for="gallery-coverflow-preview-1">発見 1</label><label class="edu-coverflow__item" for="gallery-coverflow-preview-2">発見 2</label><label class="edu-coverflow__item" for="gallery-coverflow-preview-3">発見 3</label><label class="edu-coverflow__item" for="gallery-coverflow-preview-4">発見 4</label><label class="edu-coverflow__item" for="gallery-coverflow-preview-5">発見 5</label></div><div class="edu-coverflow__dots"><label for="gallery-coverflow-preview-1"></label><label for="gallery-coverflow-preview-2"></label><label for="gallery-coverflow-preview-3"></label><label for="gallery-coverflow-preview-4"></label><label for="gallery-coverflow-preview-5"></label></div></div>',
      copy:'<div class="edu-coverflow"><input id="coverflow-1" type="radio" name="coverflow" checked><input id="coverflow-2" type="radio" name="coverflow"><input id="coverflow-3" type="radio" name="coverflow"><div class="edu-coverflow__track"><label class="edu-coverflow__item" for="coverflow-1">カード 1</label><label class="edu-coverflow__item" for="coverflow-2">カード 2</label><label class="edu-coverflow__item" for="coverflow-3">カード 3</label></div></div>'},
    {title:"自動スクロールカルーセル",className:".edu-auto-carousel",category:"motion",file:"edu-effects-3d.css",tags:"カルーセル 横流れ marquee 自動 スクロール",stage:"is-dark",
      preview:'<div class="edu-auto-carousel"><div class="edu-auto-carousel__track"><span class="edu-auto-carousel__item">観察</span><span class="edu-auto-carousel__item">比較</span><span class="edu-auto-carousel__item">発見</span><span class="edu-auto-carousel__item">整理</span><span class="edu-auto-carousel__item">観察</span><span class="edu-auto-carousel__item">比較</span><span class="edu-auto-carousel__item">発見</span><span class="edu-auto-carousel__item">整理</span></div></div>',
      copy:'<div class="edu-auto-carousel"><div class="edu-auto-carousel__track"><span class="edu-auto-carousel__item">項目A</span><span class="edu-auto-carousel__item">項目B</span><span class="edu-auto-carousel__item">項目C</span><span class="edu-auto-carousel__item">項目A</span><span class="edu-auto-carousel__item">項目B</span><span class="edu-auto-carousel__item">項目C</span></div></div>'},
    {title:"3Dホバーチルト",className:".edu-3d-tilt",category:"motion",file:"edu-effects-3d.css",tags:"3D hover チルト カード 浮く",stage:"is-grid",
      preview:'<div class="edu-card edu-card-pad edu-3d-tilt"><strong>探究カード</strong><p class="edu-card-meta">ホバーで少し浮く</p></div>',
      copy:'<article class="edu-card edu-card-pad edu-3d-tilt"><strong>カードタイトル</strong><p class="edu-card-meta">補足説明</p></article>'}
  ];
  window.EduEffectsLegacyMaterials = (window.EduEffectsLegacyMaterials || []).concat(extra);
})();